services:
  - type: web
    name: popmart-stock-checker
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
