services:
  - type: worker
    name: popmart-stock-checker
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
